### ISSUE TITLE
Visual error 

### ISSUE THREAD

**Issue by dantelewandoski** [PikalaxALT/firered-speedchoice#1]
In virdian forest fighting trainers I got this visual error 

https://prnt.sc/10yhgc2

**Comment by PikalaxALT** [comment]
Hi Dante, can you give me a rundown of the exact actions you took between the last battle and this one?

**Comment by dantelewandoski** [comment]
> Hi Dante, can you give me a rundown of the exact actions you took between the last battle and this one?

I went into virdian forest picked up the items caught 2 Pokémon regirock was the last thing I caught/fought (was using super speed because testing) and fought trainers and they just kept happening turn off speed ups to see if that was causing it and than it just kept happening for the entire rom for non gym leader/ cave trainers

**Comment by PikalaxALT** [comment]
Fixed in 98ed1ce74dba91d6eeacead74fb018e2548ac1aa
